---

---

# **Awards**

* Global Experience program 2019, Office of International Programs, American Phytopathological Society <br>
* Halse-Kentula Award 2019, Oregon State University <br>
* APS-Pacific Division meeting (2018), 3rd Place graduate student oral presentation <br>
* Anita Summers Travel Grant (2018), Botany and Plant Pathology department, Oregon State University <br>
* Plant Pathology Experiential Award (2018), American Phytopathological Society, USA <br>
* Cascadia R Conference Travel Award (2018), Portland, Oregon <br>
* Anita Summers Travel Grant (2017), Botany and Plant Pathology department, Oregon State University <br> 
* Anita Summers Travel Grant (2016), Botany and Plant Pathology department, Oregon State University <br>
* Florida Phytopathological  Society, 3rd Place Graduate Student Paper Competition (2013), Florida, USA <br>
* USAID-CIP fellowship (2012-2014), University of Florida, USA <br>
* Merit based undergraduate scholarship (2006-2010), Tribhuwan University, Nepal <br>









# **Services**

**Reviewer**<br>
Plant Pathology <br> 
Plant disease  <br> 
Journal of General Plant Pathology<br> 
MPMI <br>
Crop Protection <br>

**elife ambassdor 2019-2020**

**Departmental travel awards review committee member** <br>
Oregon State University (2016-present)<br> 

**Secretary/webmaster (2017-2018)** <br> 
Graduate Student Association <br> 
Department of Botany and Plant Pathology, OSU <br> 
 
**Secretary (2013-2104)** <br> 
Plant Pathology Graduate Student Organization <br> 
University of Florida <br> 
 
**Editor (2013-2014)** <br> 
Department of Plant Pathology Newsletter <br> 
University of Florida <br> 
 
**Member (2012-2014)** Nepalese Student Organization <br> 
University of Florida <br> 
 
**Vice President** (May 2009- April, 2010), <br> 
Nepal Youth Red Cross Circle, (1st May 2009- 30th April, 2010), Tribhuwan University <br> 
 	 
**Editor** <br> 
Agriculture Graduates Profile 2010 <br> 

